spring:
  profiles:
    active: dev
    group:
      dev:
        - local-dev
        - debug
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8084
  servlet:
    context-path: /account

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: when_authorized

security:
  jwt:
    secret: signingkey
    authorities:
      key: roles